### ISSUE TITLE
Warn im Log

### ISSUE THREAD

**Issue by totocotonio** [rg-engineering/ioBroker.daswetter#100]
Hi,
seit ein paar Tagen bekomme ich diese Warnmeldungen im LOG.
Was könnte das denn sein.
`

daswetter.0 | 2021-05-22 10:42:04.030 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswett
-- | -- | -- | --
daswetter.0 | 2021-05-22 10:42:03.979 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.931 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.886 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.837 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.789 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.744 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.668 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 1","role":"weather"}}} {"type":"channel","common":{"name":"Hour 1","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.555 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.512 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.462 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.407 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.351 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.302 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswett
daswetter.0 | 2021-05-22 10:42:03.253 | warn | (17229) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswett

`

**Comment by rg-engineering** [comment]
schau hier: #93 (vorletzter Kommentar), #96,  und hier https://forum.iobroker.net/topic/5347/adapter-daswetter/1104
Lösche alle DasWetter-DP's und lasse sie neu anlegen....

**Comment by totocotonio** [comment]
Hi,
danke für die schnelle Antwort.

Ich teste es sofort.
