### ISSUE TITLE
Es werden keine Objekte nach der Installation angelegt

### ISSUE THREAD

**Issue by lolax80** [rg-engineering/ioBroker.daswetter#101]
![Ohne Titel](https://user-images.githubusercontent.com/30566171/120835548-bd675780-c564-11eb-9bc9-3667ec1d76e8.jpg)
Ich habe den Adapter komplett deinstalliert und neu installier, doch leider werden keine Objekte angelegt.
DIe URL zu den Daten ist eingetragen.
Im LOG habe ich folgendes bei der Installation gesehen

Bitte um Hilfe

**Comment by rg-engineering** [comment]
und du hast auch gewartet, bis der Adapter gelaufen ist? Im Log zeigst du ja nur einen Teil der Installation ... Beachte, dass der Adapter ein scheduled adapter ist, d.h. der läuft nur zu bestimmten (von dir angegebenen) Zeiten. Dann legt er auch die Objekte an... Wenn er das dann immer noch nicht tut, benötige ich ein log vom run (möglichst nicht als Bildschirmfoto sondern als Text-Datei) 

Die Fehlermeldungen unten in deinem Bildschirmfoto sehen seltsam aus, kommen die bei der Installation des Adapters?

**Comment by lolax80** [comment]
Hallo, jetzt läuft der Adapter, vielen Dank. Es hat irgendwie lange gedauert bis er alles geladen hatte.
