### ISSUE TITLE
No Wether Icons

### ISSUE THREAD

**Issue by UweLoyal** [rg-engineering/ioBroker.daswetter#104]
After updating ioBroker to newest Version, I installed DASWETTER.
All works fine, but there are no icons shown!
Test with http://192.168.178.81:8081/adapter/daswetter/icons/tiempo-weather/galeria1/1.png works.
HTML for image is:
`<img src="[object Module]" alt="" height="50">`
Do you know the possible reason?
New Version of ioBroker?

Rgds
Uwe Loyal

**Comment by rg-engineering** [comment]
I don't understand the problem... a bit more information would be helpful. what datapoint do you use? Where should the adapter show an image?

**Comment by UweLoyal** [comment]
![Wetter](https://user-images.githubusercontent.com/5464553/128638220-46288e34-d594-488b-bff5-e471247fba6c.png)

This is the way the Weatherreport looks like.

![Wetter_HTML](https://user-images.githubusercontent.com/5464553/128638389-6676ab02-4133-498d-8ca9-8a547d7d445f.png)

This is like the part with icon of html looks like.

Rgds
Uwe Loyal

**Comment by UweLoyal** [comment]
![Wetter](https://user-images.githubusercontent.com/5464553/128638220-46288e34-d594-488b-bff5-e471247fba6c.png)

This is the way the Weatherreport looks like.

![Wetter_HTML](https://user-images.githubusercontent.com/5464553/128638389-6676ab02-4133-498d-8ca9-8a547d7d445f.png)

This is like the

**Comment by UweLoyal** [comment]
Sorry, closing was a mistake!

**Comment by UweLoyal** [comment]
![Wetter_Sub_HTML](https://user-images.githubusercontent.com/5464553/128638799-aa24858e-b0cf-44c7-ba03-e729fb53bf92.png)

Submenu/-info has the same Problem

**Comment by rg-engineering** [comment]
yes, sure your image source in html is wrong. But I still don't understand which adapter datapoint you try to use... The pictures above are not showing anything related to the adapter...  What visualisation object do you use? How do you configure it?
Do you use any script to calculate image source for html? 

From adapter side it looks like:

![grafik](https://user-images.githubusercontent.com/8238668/128639394-bf6a815d-c152-4696-92a9-85c1ad045713.png)

**Comment by UweLoyal** [comment]
/adapter/daswetter/icons/tiempo-weather/galeria5/SVG/Color/5.svg
for
daswetter.0.NextDays.Location_1.Day_1.iconURL

**Comment by UweLoyal** [comment]
Is the slash at the beginning the problem?

http://192.168.178.81:8081//adapter/daswetter/icons/tiempo-weather/galeria5/SVG/Color/5.svg
gets an error
Cannot GET //adapter/daswetter/icons/tiempo-weather/galeria5/SVG/Color/5.svg

http://192.168.178.81:8081/adapter/daswetter/icons/tiempo-weather/galeria5/SVG/Color/5.svg
gets a Picture
![Wetter_5](https://user-images.githubusercontent.com/5464553/128639853-a2aa9a42-4afa-4038-99d8-b25db7af59be.png)

**Comment by UweLoyal** [comment]
![DasWetter_Error](https://user-images.githubusercontent.com/5464553/128733470-80547920-fc53-4511-abc9-6f7a89ed04c9.png)

Is that helpfull for you?

**Comment by rg-engineering** [comment]
not really. This shows that adapter is doing it's job as expected. I still don't understand your problem. Please answer my questions above...
If it helps write in german or use the [forum](https://forum.iobroker.net/topic/5347/adapter-daswetter)

**Comment by UweLoyal** [comment]
Also zur Anzeige verwende ich JarVis:
![DasWetter_JarVis](https://user-images.githubusercontent.com/5464553/128745766-be4dccc3-e6a8-4164-8e36-5a2120f73e4d.png)

Anleitung habe ich hier herbekommen:
https://www.smarthome-tricks.de/software-iobroker/iobroker-jarvis-teil-13-darstellung-von-wetter-informationen/

Liegt ggf. der Fehler bei jarVis?

LG
Uwe Loyal

**Comment by rg-engineering** [comment]
dort gibt es jedenfalls ein Ticket dazu:

https://github.com/Zefau/ioBroker.jarvis/issues/827

**Comment by rg-engineering** [comment]
und hier wird das auch diskutiert:
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/4671?_=1628532975915

**Comment by rg-engineering** [comment]
können wir das Ticket hier schliessen? Am Adapter liegt das Problem ja nicht?

**Comment by UweLoyal** [comment]
Habe es noch nicht mit der empfohlenen Jarvis Version probiert, aber nach Prüfung der Infos komme ich auch zu der Schlussfolgerung, dass es an Jarvis liegt.
Report kann also geschlossen werden.

Vorschlag:
Html-String selber bauen, den man dann in Jarvis anzeigen lassen kann.
Dann gibt es auch keine Suche nach der Fehlerquelle!

Mit freundlichen Grüßen

Uwe Loyal
Am 13. Aug. 2021, 09:14 +0200 schrieb rg-engineering ***@***.***>:

**Comment by UweLoyal** [comment]
Ich habe jetzt alles mit jarvis 2.2.2 getestet, jetzt wird alles angezeigt!
Danke für die Unterstützung!

Eine Info noch:
Windicon 9, 18 und 27 in /adapter/daswetter/icons/viento-wind/galeria1/ fehlen.
![windicons](https://user-images.githubusercontent.com/5464553/129475516-7b1bae41-62c2-412c-8747-7bbb9ef68b86.png)

Ebenso geht die Icon-Steuerung teilweise nicht richtig, so werden Wind-Symbole als Wetter-Symbole angezeigt (Set 1 und Set 2). Ich vermute mal, dass dies an Jarvis liegt, da die Steuerung hier erfolgt.

LG
Uwe Loyal
