### ISSUE TITLE
DasWetter-Adapter ist a

### ISSUE THREAD

**Issue by ChrisDuck87** [rg-engineering/ioBroker.daswetter#108]
The installed Adapter is restarting all the time. 
- But link is working and i receive data from DasWetter API - each minute after restarting. 

This is the Snip of the log

daswetter.0 | 2021-08-15 12:00:05.671 | info | cleaned everything up...
daswetter.0 | 2021-08-15 12:00:05.116 | info | Terminated (NO_ERROR): Without reason
daswetter.0 | 2021-08-15 12:00:03.807 | info | starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.daswetter, node: v12.22.2, js-controller: 3.2.16

**Comment by rg-engineering** [comment]
this is a scheduled adapter, so it's the standard behaviour that adapter starts and stops. You nedd to setup, how often the adpater should run (once per hour is normally a good choice...)

![grafik](https://user-images.githubusercontent.com/8238668/129475513-1d7bebf3-e5d8-428b-9439-64362fae1e26.png)

**Comment by ChrisDuck87** [comment]
Ahh.. ok, thanks good to know :) 
then it works really well....thanks a lot for youre explanation.
