### ISSUE TITLE
Adapter startet sich regelmäßig neu

### ISSUE THREAD

**Issue by KayThe95** [rg-engineering/ioBroker.daswetter#109]
Das kommt mehrmals am Tag regelmäßig, eigentlich schon seit ich den Adapter habe. Ich wollte mal nachfragen, ob jemand weiß an was das liegen könnte. Ist das wirklich von "daswetter" aus oder kann man da lokal was machen?

```
daswetter.0 | 2021-09-10 01:45:57.930 | info | cleaned everything up...
daswetter.0 | 2021-09-10 01:45:57.391 | info | Terminated (NO_ERROR): Without reason
daswetter.0 | 2021-09-10 01:45:49.452 | info | still wrong data structure from server received! repaired...
```

**Comment by rg-engineering** [comment]
Der Adapter ist ein "scheduled" Adapter, d.h. er startet nur dann, wenn er etwas zu tun hat. Das Verhalten ist also völlig normal und gewollt. Wann er startet, stellst du ja im admin über die Zeitsteuerung ein...

**Comment by KayThe95** [comment]
Okay, vielen Dank für die Information. Nun ist es mir das alles klar (;
