### ISSUE TITLE
Fix "connectionType" and "dataSource" information

### ISSUE THREAD

**Issue by klein0r** [rg-engineering/ioBroker.daswetter#114]
Should be

```
"connectionType": "cloud",
"dataSource": "poll",
```

instead of

https://github.com/rg-engineering/ioBroker.daswetter/blob/cb59649c780970510759f2f7b0057158c40c4537/io-package.json#L135-L136

Documentation: https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md#connection-types

**Comment by rg-engineering** [comment]
done with 3.0.9
