### ISSUE TITLE
error exception in getForecastDataHourlyJSON

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.daswetter#131]
Hallo,

Error seit Update auf Version 3.1.1  

daswetter.0 | 2022-03-20 13:00:23.662 |  [TypeError: Assignment to constant variable.]

Plattform: Windows
RAM: 16 GB 
NODE.JS: V14.19.1
NPM: 6.14.16
JS Controller: 4.0.21
Admin: 5.3.3
Socket.io: 4.1.4
Script Engine: 5.4.3
VIS: 1.4.12

**Comment by rg-engineering** [comment]
already reported and closed with 3.1.2 : #130
