### ISSUE TITLE
detaillierte Informationen für alle 3 Stunden liefert Werte für jede Stunde

### ISSUE THREAD

**Issue by anno171986** [rg-engineering/ioBroker.daswetter#133]
Obwohl ich bei den Einstellungen nur Pfad 1 und Pfad 2 angegeben habe, sind unter Objelten Werte für alle 24h vorhanden:

daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1
...
daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_24

Das war in der Vergangenheit nicht so und sollte meiner Meinung nach auch nicht so sein.

daswetter.0 v3.0.9

**Comment by rg-engineering** [comment]
Verstehe ich nicht:
* Pfad 1 (XML-Datei mit 7-Tage-Wettervorhersage und Tagesübersicht) füllt **NextDays**
* Pfad 2 ( XML-Datei mit 5-Tage-Wettervorhersage und detaillierten Informationen für alle 3 Stunden) füllt **NextDaysDetailed**
* Pfad 3 (XML-Datei mit Wettervorhersage für die nächsten 5 Tage und stündliche Informationen) füllt **NextHours**
* Pfad 4 (JSON-Datei mit Wettervorhersage für die nächsten 5 Tage und stündliche Informationen) füllt **NextHours2**

Wenn du also die ersten beiden Pfade angegeben hast, werden die komplett interpretiert....

**Comment by anno171986** [comment]
Aber wieso füllt er denn bei NexDaysDetailed 24 Stunden? Es sollte ja nur alle 3 Stunden ein Ordner angelegt werden. Das war ja vorher auch so.

Ich habe jetzt die Ordner 9 bis 24 gelöscht, weil sie auch schon 2 Tage nicht aktualisiert wurden, gucken ob sie wieder angelegt werden.
