### ISSUE TITLE
Messwerte der eigenen Wetterstation ans Netzwerk Wetter.com senden

### ISSUE THREAD

**Issue by Goersch** [rg-engineering/ioBroker.daswetter#137]
Hallo,

ich möchte die Daten meiner Wetterstation dem Netzwerk Wetter.com zur Verfügung stellen.

Würde mich deshalb um eine entsprechende Erweiterung des Adapters freuen.

Gruss&Danke :)
Georg

**Comment by rg-engineering** [comment]
Bitte beachte, die Daten hier kommen von [daswetter.com](daswetter.com) und nicht von [wetter.com](wetter.com) .
Ein Daten-upload zu DasWetter.com ist mir nicht bekannt...

**Comment by Goersch** [comment]
ups, verwirrend : danke für die Info
