### ISSUE TITLE
Mond Icon Eintrag fehlt

### ISSUE THREAD

**Issue by bergjet** [rg-engineering/ioBroker.daswetter#139]
**Versions:**  
 - Adapter version: 3.1.2
 
Der Pfad Eintrag in den Objekten fehlt für die Mond Icons.
<img width="1543" alt="Bildschirmfoto 2022-04-27 um 15 53 14" src="https://user-images.githubusercontent.com/4241968/165536019-5bc0a24f-c8b1-4f7f-9019-302c84337025.png">

**Comment by bergjet** [comment]
Neu installiert, fehlt noch immer.

**Comment by rg-engineering** [comment]
solved with 3.1.3

**Comment by bergjet** [comment]
Thanks, it's now ok.
