### ISSUE TITLE
add sunrise, sundown and moon information

### ISSUE THREAD

**Issue by daniel-2k** [rg-engineering/ioBroker.daswetter#14]
I use the adapter to display weather information on a weather panel with ioBroker.vis.
It would be usefull if the adapter can provide the sunrise sundown time and moon information (luminescence would be sufficent for me).
The will provide this information:
```
"sun":{"in":"05:40","mid":"13:29","out":"21:18"},
"moon":{"in":"13:22","out":"00:33","lumi":"45.76%","desc":"zunehm. Mond, 45.76% Beleuchtet","symbol":"7"}
```

**Comment by rg-engineering** [comment]
this (and much more) will be supported with V 2.x.x of the adapter. If you want you can install V2.0.0 already from github (but this version is not released yet, since few features are still in development)

**Comment by daniel-2k** [comment]
I already tried out the new version 2.0.0 from GitHub. This versions is working better than the current version. The old version cancels any operation which takes longer than 6000 ms which is bad because some requests take much longer.
But one notice to the new data structure:
Why you separating value and unit into two different data points? That’s unnecessary. Every datapoint has a value as a property.

**Comment by rg-engineering** [comment]
I'll consider...
Idea was to parse date as they come from server. But I agree it does not make sense for units.

**Comment by rg-engineering** [comment]
in latest version 2.1.1 I parse units and use it to create objects. Keep in mind I can not update an already existing object. So only the first time when objects are created unit from data structure is used...
