### ISSUE TITLE
Missing Moon Icon URL in daswetter.0.NextDaysDetailed.Location_1.Day_1.moonIconURL

### ISSUE THREAD

**Issue by baennjer** [rg-engineering/ioBroker.daswetter#140]
In v 3.1.2 the Datapoint "daswetter.0.NextDaysDetailed.Location_1.Day_1.moonIconURL"  is not filled with the Moon Icon URL, it's just empty...

**Comment by rg-engineering** [comment]
see #139: it's already fixed

**Comment by baennjer** [comment]
Thanks.
Sorry I didnt check the closed issues.
