### ISSUE TITLE
Sonnenscheindauer pro Stunde

### ISSUE THREAD

**Issue by Baenker** [rg-engineering/ioBroker.daswetter#142]
ich nutze den Adapter mit der stündlichen Auflösung und 5 Tage (Pfad3).

Dort gibt es ein Feld pro Tag mit der Sonnenscheindauer. Mir fehlt die Sonnenscheindauer pro Stunde.

Ich habe mal ein wenig die Api mir angeguckt:

https://www.meteomatics.com/en/api/available-parameters/sun/

Wie es aussieht sollte das möglich sein?

sunshine_duration_<interval>:<unit>

Available intervals: 1h, 3h, 6h, 12h, 24h
Available Units: h, min

Wäre schön wenn man das aufnehmen könnte. Ich verschiebe derzeit meine Dämmerung Morgens und Abends je nach Sonnenschein. Das ist natürlich sehr ungenau wenn es 5 Stunden Sonne am Tag gibt können die nur Morgens sein so das es Morgens früher hell ist.

Die Angaben könnten aber auch bei der Bewässerung besser berücksichtigt werden.

**Comment by Baenker** [comment]
ok. Ich schließe es wieder. Scheint in der freien Api nicht vorhanden zu sein...

**Comment by thebilberry** [comment]
Trotz "closed" würde ich gern hier noch mal interessehalber eine Frage zur Sonnenscheindauer anschließen:

Bei Nutzung von "Pfad 3" wird diese im Datenpunkt `daswetter.0.NextHours.Location_1.Day_2.sunshineDuration` eingetragen. In der XML-Datei selbst konnte ich die Werte jedoch nicht finden. 

Wie werden die Dauern vom Adapter ermittelt/berechnet?
