### ISSUE TITLE
Random Error messages every couple of days

### ISSUE THREAD

**Issue by steffensammet** [rg-engineering/ioBroker.daswetter#144]
Every couple of days, I got error messages like this. There is no interaction with the adapter from my side.

**Expected behavior**  
From time to time, I got error messages in my log as you can see on the screenshot.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/38013126/190249676-7884e643-5f2f-4399-80aa-8815916391ff.png)

**Versions:**  
 - Adapter version: 3.1.4
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Rasbian

**Additional context**

**Comment by aruttkamp** [comment]
Same here.

![05-10-_2022_08-12-12](https://user-images.githubusercontent.com/1271404/193993168-5b8d9403-f6fb-492c-9394-3503a9d29975.jpg)

**Comment by rg-engineering** [comment]
please give more time to the adapter to parse the data. increase the timout here:
![grafik](https://user-images.githubusercontent.com/8238668/194148610-6058f0d5-8e3a-4a54-97f4-067000a72de0.png)

**Comment by aruttkamp** [comment]
thx for advice ! now it is ok ! No more Errors ! 
Issue can be closed for me.
