### ISSUE TITLE
Mir werden keine Icons angezeigt

### ISSUE THREAD

**Issue by Damrak2022** [rg-engineering/ioBroker.daswetter#146]
Mein Flow sieht folgendermassen aus. Weiterhin auch ein Screenshot aus der function node.
Wenn ich die von mir benutzte Url aufrufe , bekomme ich eine 400 ungültige Anfrage.
Hier meine URL: https://raw.githubusercontent.com/rg-engineering/ioBroker.daswetter/master/admin/icons/tiempo-weather/galeria1/Wie müsste die URL korrekt aussehen, damit mir die Icons angezeigt werden?
Es wäre klasse, wenn du mir das mal sagen würde, da ich mich mit solchen Dingen noch schwer tue.

Gruß Andy
![Uploading Bildschirmfoto 2022-10-20 um 19.27.58.png…
<img width="741" alt="Bildschirmfoto 2022-10-20 um 19 28 11" src="https://user-images.githubusercontent.com/101031627/197017911-ba65af03-8cd6-4e8c-a748-df1fa23d9c2e.png">
]()

**Comment by rg-engineering** [comment]
Der Adapter legt doch die entsprechenden Datenpunkte an, da steht dann der lokale Pfad drin:
![grafik](https://user-images.githubusercontent.com/8238668/197019312-ed185ab4-f1ee-4915-971e-05b0d2cca2d6.png)

Deine URL zeigt irgendwo in's github... Dein Bildschirmfoto sehe ich leider nicht, somit weiß ich auch nicht, was du eigentlich vorhast...

**Comment by rg-engineering** [comment]
evtl auch mal im Forum suchen:
https://forum.iobroker.net/topic/5347/adapter-daswetter/
oder 
https://forum.iobroker.net/topic/28717/vis-von-sigi234
