### ISSUE TITLE
REGISTRIEREN SIE SICH: WETTER-API nicht möglich!

### ISSUE THREAD

**Issue by Maell0** [rg-engineering/ioBroker.daswetter#147]
Hallo!

Möchte mich  gerne registrieren. Doch leider ist dies nicht möglich.

Es wird immer gemeldet: "Ein Benutzer mit dieser E-Mail-Adresse existiert bereits". Habe dies mit mehrere Email-Adressen (mit denen ich nicht garantiert noch nie angemeldet habe) getestet und auch verschieden Browser. Leider ohne Erfolg!

Versuche ich mich mit einer dieser angeblich existierenden Adresse anzumelden, wird natürlich gemeldet, daß ich kein registrierter Benutzer bin.

Was nun?

Gruss Marcel

**Comment by rg-engineering** [comment]
Aus meiner Sicht funktioniert das Passwort zurücksetzen:
URL [DasWetter](https://www.daswetter.com/api/#/login) aufrufen

In das erste Feld klicken und per tab auf "Passwort vergessen" navigieren
![grafik](https://user-images.githubusercontent.com/8238668/198817292-c7f18a2d-7192-47a8-b2f2-95bc3b231ac8.png)

und Enter drücken. 
dort die email eingeben:
![grafik](https://user-images.githubusercontent.com/8238668/198817316-3b3e9072-12fa-487d-b52d-3541eae2f5d0.png)



oder alternativ direkt die URL [Haben Sie Ihr Passwort vergessen](https://www.daswetter.com/api/#/passwordRecovery) aufrufen

**Comment by rg-engineering** [comment]
Neuregistrierung scheint aktuell bei DasWetter nicht zu funktionieren. Ich habe dort ein Ticket eröffnet...
