### ISSUE TITLE
daswetter API timeout handling

### ISSUE THREAD

**Issue by usrflo** [rg-engineering/ioBroker.daswetter#15]
I wondered why object values were *not* or very rarely updated although the debug log showed to me that the update is OK:

```
host.DiskStation | 2018-07-29 14:00:11.415 | info | instance system.adapter.daswetter.0 terminated with code 0 (OK)
-- | -- | -- | --
daswetter.0 | 2018-07-29 14:00:11.379 | debug | cleaned everything up...
daswetter.0 | 2018-07-29 14:00:11.377 | debug | cleaned everything up...
daswetter.0 | 2018-07-29 14:00:11.363 | debug | cleaned everything up...
daswetter.0 | 2018-07-29 14:00:05.315 | debug | calling forecast: http://api.daswetter.com/index.php?api_lang=de&localidad=...&affiliate_id=...&v=2.0&h=1
daswetter.0 | 2018-07-29 14:00:04.888 | info | starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.daswetter, node: v6.14.2

```

I solved the update problem by simply changing the cron setting from
```
0,30 * * * *
```
to arbitrary minutes because the API server does respond late on exact hours, half hours and so on. (server overload problem).
In the logs above I see that the timeout of the npm request method was triggered after about 10 seconds.

So I propose the following changes to the adapter:

* add a hint to the adapter settings dialog about this API server load problem so people choose random cron configurations by themselves

* assure that log output refers to a connection or read timeout that is checked according to https://www.npmjs.com/package/request#timeouts so people become aware of the problem. The adapter should not terminate with "code 0 (OK)" in such an error case.

* an improvement to the iobroker project: propose random cron defaults to the user on adapters like this one to prevent overload on external services.

BTW: thanks for providing this adapter +1

**Comment by rg-engineering** [comment]
timeout handling is already overworked in 2.xx but I'll consider your ideas. Thanks for the feedback...
