### ISSUE TITLE
IObroker im Docker Container. 

### ISSUE THREAD

**Issue by g3orgs** [rg-engineering/ioBroker.daswetter#17]
URLS eingetragen,
leider können die Einstellungen nicht gespeichert werden. 
Also Speicher Button geht wird dann grau, aber beim Schließen kommt folgende Meldung. 
Berechtigungsproblem? Wo werden die URLS abgelegt? 

Bitte bestätigen
Einige Daten sind nicht gespeichert. Verwerfen?

**Comment by GermanBluefox** [comment]
Please try again, when merged: https://github.com/rg-engineering/ioBroker.daswetter/pull/18

**Comment by rg-engineering** [comment]
it is included in V2.1.2
