### ISSUE TITLE
wrong unit at daswetter.0.NextDays.Location_1.Day_1.Maximale_Temperatur_value

### ISSUE THREAD

**Issue by MeisterTR** [rg-engineering/ioBroker.daswetter#19]
![2018-08-17_05h13_02](https://user-images.githubusercontent.com/6328382/44246025-3fcbd480-a1dc-11e8-8db2-567ef916562a.png)

**Comment by rg-engineering** [comment]
I just fixed that typo here. You should delete that datapoint and it will created with correct unit next run time..
