### ISSUE TITLE
	Error: exception in HourlyForecast [TypeError: Cannot read properties of undefined (reading 'city')]

### ISSUE THREAD

**Issue by latzi0710** [rg-engineering/ioBroker.daswetter#217]
Since a few days i receive the above mentioned error every scheduled adapter start, here the log:
```
host.ioBroker | 2023-08-27 11:41:47.400 | info | instance system.adapter.daswetter.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
daswetter.0 | 2023-08-27 11:41:47.321 | info | cleaned everything up...
daswetter.0 | 2023-08-27 11:41:46.808 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): All data handled, adapter stopped until next scheduled moment
daswetter.0 | 2023-08-27 11:41:43.268 | info | still wrong data structure from server received! repaired...
daswetter.0 | 2023-08-27 11:41:43.199 | error | exception in HourlyForecast [TypeError: Cannot read properties of undefined (reading 'city')]
daswetter.0 | 2023-08-27 11:41:38.850 | info | starting. Version 3.1.10 in /opt/iobroker/node_modules/iobroker.daswetter, node: v18.17.1, js-controller: 5.0.12
host.ioBroker | 2023-08-27 11:41:37.461 | info | instance system.adapter.daswetter.0 started with pid 504129
host.ioBroker | 2023-08-27 11:41:37.438 | info | instance scheduled system.adapter.daswetter.0 */30 * * * *
```

**Comment by Elvissimo** [comment]
same here since 23.8. , only path 4, the JSON link is working for me

**Comment by rg-engineering** [comment]
can you please call your URL in a browser? should look like:

![grafik](https://github.com/rg-engineering/ioBroker.daswetter/assets/8238668/591d342f-2cab-4717-8554-3e1eb4486692)

**Comment by latzi0710** [comment]
here it comes:
```
<report>
<location city="Tragwein [Oberösterreich;Österreich]">
<interesting>
<url description="Vorhersage">https://www.daswetter.com/wetter_Tragwein-Europa-osterreich-Oberosterreich--1-195737.html</url>
</interesting>
<var>
<name>Minimale Temperatur</name>
<icon>4</icon>
<data>
<forecast data_sequence="1" value="16"/>
<forecast data_sequence="2" value="16"/>
<forecast data_sequence="3" value="13"/>
<forecast data_sequence="4" value="13"/>
<forecast data_sequence="5" value="10"/>
<forecast data_sequence="6" value="11"/>
<forecast data_sequence="7" value="12"/>
</data>
</var>
<var>
<name>Maximale Temperatur</name>
<icon>5</icon>
<data>
<forecast data_sequence="1" value="24"/>
<forecast data_sequence="2" value="24"/>
<forecast data_sequence="3" value="19"/>
<forecast data_sequence="4" value="18"/>
<forecast data_sequence="5" value="22"/>
<forecast data_sequence="6" value="25"/>
<forecast data_sequence="7" value="28"/>
</data>
</var>
<var>
<name>Wind</name>
<icon>9</icon>
<data>
<forecast data_sequence="1" id="15" idB="47" value="Mäßiger Wind aus Westen" valueB="Mäßiger Wind aus Westen"/>
<forecast data_sequence="2" id="10" idB="50" value="Mäßiger Wind aus Nordosten" valueB="Mäßiger Wind aus Nordosten"/>
<forecast data_sequence="3" id="15" idB="47" value="Mäßiger Wind aus Westen" valueB="Mäßiger Wind aus Westen"/>
<forecast data_sequence="4" id="15" idB="47" value="Mäßiger Wind aus Westen" valueB="Mäßiger Wind aus Westen"/>
<forecast data_sequence="5" id="15" idB="47" value="Mäßiger Wind aus Westen" valueB="Mäßiger Wind aus Westen"/>
<forecast data_sequence="6" id="33" idB="25" value="Wechselnder Wind" valueB="Leichter Wind aus Norden"/>
<forecast data_sequence="7" id="33" idB="34" value="Wechselnder Wind" valueB="Mäßiger Wind aus Nordosten"/>
</data>
</var>
<var>
<name>Wetter Symbol</name>
<icon>10</icon>
<data>
<forecast data_sequence="1" id="12" id2="12" value="Bewölkt mit stürmischen Regenschauern" value2="Bewölkt mit stürmischen Regenschauern"/>
<forecast data_sequence="2" id="13" id2="13" value="Bedeckt mit stürmischen Regenschauern" value2="Bedeckt mit stürmischen Regenschauern"/>
<forecast data_sequence="3" id="6" id2="6" value="Bewölkt mit leichtem Regen" value2="Bewölkt mit leichtem Regen"/>
<forecast data_sequence="4" id="6" id2="6" value="Bewölkt mit leichtem Regen" value2="Bewölkt mit leichtem Regen"/>
<forecast data_sequence="5" id="2" id2="2" value="Teils bewölkt" value2="Teils bewölkt"/>
<forecast data_sequence="6" id="2" id2="2" value="Teils bewölkt" value2="Teils bewölkt"/>
<forecast data_sequence="7" id="2" id2="2" value="Teils bewölkt" value2="Teils bewölkt"/>
</data>
</var>
<var>
<name>Tag</name>
<icon>15</icon>
<data>
<forecast data_sequence="1" value="Sonntag"/>
<forecast data_sequence="2" value="Montag"/>
<forecast data_sequence="3" value="Dienstag"/>
<forecast data_sequence="4" value="Mittwoch"/>
<forecast data_sequence="5" value="Donnerstag"/>
<forecast data_sequence="6" value="Freitag"/>
<forecast data_sequence="7" value="Samstag"/>
</data>
</var>
<var>
<name>Wetterbedingungen</name>
<icon>19</icon>
<data>
<forecast data_sequence="1" value="Während der ersten Hälfte des Tages Teils bewölkt tendenziell in der zweiten Hälfte des Tages Teils bewölkt mit starken Regenschauern"/>
<forecast data_sequence="2" value="Während der ersten Hälfte des Tages Bewölkt mit leichtem Regen tendenziell in der zweiten Hälfte des Tages Teils bewölkt mit starken Regenschauern"/>
<forecast data_sequence="3" value="Während der ersten Hälfte des Tages Bewölkt mit leichtem Regen tendenziell in der zweiten Hälfte des Tages Teils bewölkt"/>
<forecast data_sequence="4" value="Während der ersten Hälfte des Tages Bewölkt mit leichtem Regen tendenziell in der zweiten Hälfte des Tages Teils bewölkt"/>
<forecast data_sequence="5" value="Den ganzen Tag über Sonne"/>
<forecast data_sequence="6" value="Den ganzen Tag über Sonne"/>
<forecast data_sequence="7" value="Den ganzen Tag über Sonne"/>
</data>
</var>
</location>
</report>
```

**Comment by rg-engineering** [comment]
that looks well. Can you please create a debug log?

**Comment by latzi0710** [comment]
sure, it´s  a long log, so i can´t post it as text here - attached as txt-file
[DasWetterLog.txt](https://github.com/rg-engineering/ioBroker.daswetter/files/12448472/DasWetterLog.txt)

**Comment by rg-engineering** [comment]
It seems data provider (DasWetter.com) has an problem. In log I see

> Der gesuchte Ort existiert nicht. Versuchen Sie es mit einer anderen Ortschaft oder wenden Sie sich an den Webmaster (info@daswetter.com)

as an result of calling the URL.  I see the exception only on hourly forecast.  7 days forecast,  5 days forecast and JSON forecast are working well.
Interesting, that we get data if we call the URL in browser...

**Comment by latzi0710** [comment]
unfortunately the datapoints are not written due to this error, so meanwhile i will pick a neighbouring town.

**Comment by bergjet** [comment]
same here since 28.8.

**Comment by PastCoder** [comment]
And same also here. 

Access to the URL in the browser works but iobroker reports an error.
But one though regarding that:
The browser replaces http automatically with https. And more and more sites and tools push the users to use https.
So I changed the URL in the adapter settings also to https.....and now the error seems to be gone (at least after first fee cycles).

**Comment by PastCoder** [comment]
My previous comment seem to solve the issue:
Change in the URLs in the adapter settings the "http" to "https".

**Comment by bergjet** [comment]
Have switched to https, but after a week the error is back.

**Comment by PastCoder** [comment]
At the same day it was also back for me. 
Now it works again without the error.
Maybe it was just a temporary access problem on that day.
@bergjet Does it work today with or without error at your setup?

**Comment by bergjet** [comment]
> @bergjet Does it work today with or without error at your setup?
Today, 07.10.2023 with https it works.

**Comment by Diginix** [comment]
Same here since some days multiple times per day but for "7DaysForecast":
`exception in 7DaysForecast [TypeError: Cannot read properties of undefined (reading 'city')]n `

**Comment by bergjet** [comment]
I have to switch from https to http every few days and then back again.

**Comment by lammy000** [comment]
Hi, 

i have the same problem. It is not possible which version for my isue ... everything the same :(

exception in 5DaysForecast [TypeError: Cannot read properties of undefined (reading 'city')]

`http://[api.daswetter.com/index.php?api_lang=de&localidad=100182&affiliate_id=4s5u4jv1lxap&v=2.0](http://api.daswetter.com/index.php?api_lang=de&localidad=100182&affiliate_id=4s5u4jv1lxap&v=2.0)`

`<report>
<location city="Ehmen [Wolfsburg;Deutschland]">
<interesting>
<url description="Vorhersage">https://www.daswetter.com/wetter_Ehmen-Europa-Deutschland-Niedersachsen--1-100182.html</url>
</interesting>
<day value="20231105" name="Sonntag">
<symbol value="6" desc="Bewölkt mit leichtem Regen" value2="6" desc2="Bewölkt mit leichtem Regen"/>
<tempmin value="9" unit="°C"/>
<tempmax value="12" unit="°C"/>
<wind value="31" unit="km/h" symbol="23" symbolB="63"/>
<wind-gusts value="61" unit="km/h"/>
<rain value="5.8" unit="mm"/>
<humidity value="84"/>
<pressure value="979" unit="mb"/>
<snowline value="1500" unit="m"/>
<uv_index_max value="1"/>
<sun in="07:20" mid="12:01" out="16:41"/>
<moon in="23:02" out="14:35" lumi="49.06%" desc="abneh. Mond, 49.06% Beleuchtet" symbol="21"/>
<local_info local_time="11:12" offset="1"/>
<hour value="02:00">
<temp value="9" unit="°C"/>
<symbol value="6" desc="Bewölkt mit leichtem Regen" value2="6" desc2="Bewölkt mit leichtem Regen"/>
<wind value="16" unit="km/h" dir="S" symbol="13" symbolB="45"/>
<wind-gusts value="30" unit="km/h"/>
<rain value="0.1" unit="mm"/>
<humidity value="81"/>
<pressure value="977" unit="mb"/>
<clouds value="70%"/>
<snowline value="1600" unit="m"/>
<windchill value="7" unit="°C"/>
<uv_index value="0"/>
</hour>`

**Comment by SirFlour** [comment]
me too, i have the same problem. :(

**Comment by tomschlde** [comment]
Seems to be a problem with the api on the server side.
Even the new search for the home location and re-generating the api-calls leads to the same error - sometimes "daswetter" forgets the existenc of the location.
In my case i change the call to a location nearby - until this does'nt work anymore. Then i change back to my home location.

**Comment by Hant0r** [comment]
Is there still no solution to the bug?

**Comment by theflyer08** [comment]
Same here - I got the same error message.

**Comment by Stefan-CH-87** [comment]
Weiterhin Fehler im Log:  `exception in 5DaysForecast [TypeError: Cannot read properties of undefined (reading 'city')] got <?xml version="1.0" encoding="UTF-8" ?><report><error>Der gesuchte Ort existiert nicht. Versuchen Sie es mit einer anderen Ortschaft oder wenden Sie sich an den Webmaster (info@daswetter.com).</error></report>`

Update auf 3.1.12 gemacht.

**Comment by rg-engineering** [comment]
ja, aber das log erklärt den Grund: "Der gesuchte Ort existiert nicht. Versuchen Sie es mit einer anderen Ortschaft oder wenden Sie sich an den Webmaster (info@daswetter.com)" 
Das kann der Adapter nicht beheben, das ist eine Fehlermeldung von DasWetter...

**Comment by bergjet** [comment]
Wenn man den API-Pfad von https auf http wechselt, dann findet er den Ort. Das geht ca. 1 Woche. Dann kommt der Fehler wieder. Wechselt man dann wieder zurück von http auf https dann funktioniert es wieder ca 1 Woche. usw...

**Comment by Stefan-CH-87** [comment]
Habe jetzt mal ein E-Mail gesendet. Ist schon komisch, das es nach gut 1 Jahr pltözlich auftaucht und vorher hat der Ort existiert. Er findet ihn auch wenn ich ihn Suche auf der Homepage von daswetter.com

**Comment by Diginix** [comment]
Ich erhalte mit v3.1.12 nun diesen Grund für die exeption:
`2023-12-30 20:27:55.832 -error: daswetter.0 (958118) exception in 7DaysForecast [TypeError: Cannot read properties of undefined (reading 'city')] got <?xml version="1.0" encoding="UTF-8" ?><report><error>Sie sind kein registrierter Benutzer der daswetter.com-API oder Ihr Konto wurde nicht aktiviert.</error></report>
`
Men Konto ist aber aktiviert und wenn ich eingeloggt unter https://www.daswetter.com/api/#/board/einOrt meinen Ort eingebe, erhalte ich auch eine XML URL für die7 Tage Vorhersage. Der Abruf der XML liefert dann aber eben genau den Fehler, dass mein Konto nicht aktiviert wäre.

**Comment by bergjet** [comment]
Manchmal geht es von selbst wieder. Vielleicht ist die Wartezeit des Adapter zu kurz, bis die Meldung vom Server kommt.

**Comment by Diginix** [comment]
> Manchmal geht es von selbst wieder. Vielleicht ist die Wartezeit des Adapter zu kurz, bis die Meldung vom Server kommt.

Mein Fehler hat nichts mit Wartezeit zu tun. Auch das manuelle Abrufen der XML liefert den Fehler mit angeblich nicht aktiviertem Konto.

**Comment by rg-engineering** [comment]
no adapter problem
