### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by Xyolyp** [rg-engineering/ioBroker.daswetter#22]
The first request seems to be successfull (about a month ago) but after that no new data was gathered.
When requesting the used URL (variant 4 JSON) in a browser I receive all the JSON that contains recent data. I deleted all the datapoints and waited for the next execution but only this single one was recreated. (daswetter.0.NextHours2.Location_1.Location)
I have two instances with different locations and both have the exact same issue. I can assist you searching the error in any way you'd like.
log:
`

daswetter.0 | 2018-10-01 21:18:04.608 | debug | nothing to do
-- | -- | -- | --
daswetter.0 | 2018-10-01 21:18:04.372 | debug | back to list: NextHours2.Location_1.Location Uetersen
daswetter.0 | 2018-10-01 21:18:04.080 | debug | objects in list: 2
daswetter.0 | 2018-10-01 21:18:04.078 | debug | got undefined days
daswetter.1 | 2018-10-01 21:18:03.239 | debug | objects in list: 2
daswetter.1 | 2018-10-01 21:18:03.237 | debug | got undefined days
daswetter.1 | 2018-10-01 21:18:02.965 | debug | calling forecast hourly JSON: http://api.daswetter.com/index.php?api_lang=de&localidad=105205&affiliate_id=xxxxxxxxxxxxxx&v=3.0
daswetter.1 | 2018-10-01 21:18:02.946 | debug | using new datastructure
daswetter.1 | 2018-10-01 21:18:02.935 | debug | checking data structures
daswetter.1 | 2018-10-01 21:18:02.931 | debug | deleting unused dataset
daswetter.1 | 2018-10-01 21:18:02.930 | debug | set timeout to 300 sec
daswetter.0 | 2018-10-01 21:18:02.938 | debug | got 0 channels
daswetter.0 | 2018-10-01 21:18:02.934 | debug | got 0 states
daswetter.0 | 2018-10-01 21:18:02.834 | debug | calling forecast hourly JSON: http://api.daswetter.com/index.php?api_lang=de&localidad=27502&affiliate_id=xxxxxxxxxxxxxxx&v=3.0
daswetter.0 | 2018-10-01 21:18:02.817 | debug | using new datastructure
daswetter.0 | 2018-10-01 21:18:02.808 | debug | checking data structures
daswetter.0 | 2018-10-01 21:18:02.806 | debug | deleting unused dataset
daswetter.0 | 2018-10-01 21:18:02.805 | debug | set timeout to 300 sec

`

**Comment by rg-engineering** [comment]
Can you try to disable one instance and check again? you run both instances at almost the same time... The log "got undefined days" says there are no data in json (or json has a different structure). So it would be good to see the json (probably logged in browser).

**Comment by rg-engineering** [comment]
see also
https://forum.iobroker.net/viewtopic.php?f=20&t=18189#p190224

**Comment by truegreyhound** [comment]
I think this is not a problem in the structur of the json data. The problem is the incorrect command too get the count of days. Try "Object.keys(result.day).length" instead "result.day.length", then the next loop for the days should start with "1" --> "for (let d = 1; d =< numOfDays; d++) {" and then "d" == "dd" and so on. I don't know, is this an problem with the js-version or other, my version is 8.14.

**Comment by rg-engineering** [comment]
the problem is solved already with latest version. I "repair" the data structure if I detect wrong version. You can try it with latest github version, it's not published yet on NPM...
