### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by simone1999** [rg-engineering/ioBroker.daswetter#23]
hello, this Adapter always throw Errors in my log. The Data points do refresh, so i'm still able to use this Adapter, but it spams my Log with Error Messages.
the exact log is:

daswetter.0 | 2018-10-12 09:52:06.015 | error | at WS.Transport.onPacket  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:145:8)
-- | -- | -- | --
daswetter.0 | 2018-10-12 09:52:06.015 | error | at WS.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at WS.<anonymous>  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:268:10)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at Socket.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:451:14)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:322:16)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:237:14)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at decodeString (/opt/iobroker/node_modules/socket.io-parser/index.js:325:9)
daswetter.0 | 2018-10-12 09:52:06.015 | error | at tryParse (/opt/iobroker/node_modules/socket.io-parser/index.js:336:12)
daswetter.0 | 2018-10-12 09:52:06.015 | error | RangeError: Maximum call stack size exceeded
daswetter.0 | 2018-10-12 09:52:06.013 | error | uncaught exception: Maximum call stack size exceeded

**Comment by rg-engineering** [comment]
to solve that issue I need some more information:
* how many and which data path do you use?
* how often do you call to update?
* which system and OS do you use?
* are there more and other logs available? Probably you can switch to debug mode and send the log again?

**Comment by simone1999** [comment]
thanks for your fast response, here are the additional Informations:

how many and which data path do you use?
I use all 4 paths (first Link is the standard one, 2. with &v=2.0, 3. with &v=2.0&h=1 and 4. with &v=3.0)
before the addition of the json Data Structure Link in your project it worked fine.

how often do you call to update?
every 30 Minutes

which system and OS do you use?
I use an Rock64(like an Raspberry Pi but with 4GB of Ram) and it runs a nightly Debian build (but it worked on this exact Hardware some Time ago)

are there more and other logs available? Probably you can switch to debug mode and send the log again?
Here they are:


host.ioBroker-Rock64 | 2018-10-12 18:58:06.962 | info | instance system.adapter.daswetter.0 terminated with code 0 (OK)
-- | -- | -- | --
daswetter.0 | 2018-10-12 18:58:06.846 | debug | update already running
daswetter.0 | 2018-10-12 18:58:06.845 | debug | got undefined days
daswetter.0 | 2018-10-12 18:58:06.723 | debug | calling  forecast hourly JSON:  http://api.daswetter.com/index.php?api_lang=de&localidad=27062&affiliate_id=tzb7n666mtui&v=3.0
daswetter.0 | 2018-10-12 18:58:06.723 | debug | update already running
daswetter.0 | 2018-10-12 18:58:06.722 | debug | hourly forecast done, objects in list 2639
daswetter.0 | 2018-10-12 18:58:06.417 | error | RangeError: Maximum call stack size exceeded     at exports.active (timers.js:152:3)     at createSingleTimeout (timers.js:486:3)     at setTimeout (timers.js:466:10)     at Socket.onHeartbeat (/opt/i
daswetter.0 | 2018-10-12 18:58:06.417 | error | uncaught exception: Maximum call stack size exceeded
daswetter.0 | 2018-10-12 18:58:06.416 | debug | got 129 channels
host.ioBroker-Rock64 | 2018-10-12 18:58:06.322 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
tankerkoenig.0 | 2018-10-12 18:58:06.113 | info | objects written
tankerkoenig.0 | 2018-10-12 18:58:05.811 | info | starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.tankerkoenig, node: v8.12.0
daswetter.0 | 2018-10-12 18:58:05.106 | debug | calling  forecast hourly:  http://api.daswetter.com/index.php?api_lang=de&localidad=27062&affiliate_id=tzb7n666mtui&v=2.0&h=1
daswetter.0 | 2018-10-12 18:58:05.106 | debug | update already running
daswetter.0 | 2018-10-12 18:58:05.104 | debug | 5 days forecast done, objects in list 1053
daswetter.0 | 2018-10-12 18:58:02.622 | debug | calling  forecast 5 days:  http://api.daswetter.com/index.php?api_lang=de&localidad=27062&affiliate_id=tzb7n666mtui&v=2.0
daswetter.0 | 2018-10-12 18:58:02.622 | debug | objects in list: 107
daswetter.0 | 2018-10-12 18:58:02.621 | debug | 7 days forecast done, objects in list 107
daswetter.0 | 2018-10-12 18:58:02.369 | debug | calling forecast 7 days: http://api.daswetter.com/index.php?api_lang=de&localidad=27062&affiliate_id=tzb7n666mtui
daswetter.0 | 2018-10-12 18:58:02.369 | debug | using new datastructure
daswetter.0 | 2018-10-12 18:58:02.369 | debug | checking data structures
daswetter.0 | 2018-10-12 18:58:02.369 | debug | deleting unused dataset
daswetter.0 | 2018-10-12 18:58:02.369 | debug | set timeout to 300 sec
daswetter.0 | 2018-10-12 18:58:02.369 | info | starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.daswetter, node: v8.12.0

The really strange thing is, that it sometimes work without anny Error, then sometimes it throws only the 2 Errors seen in this log and in a nother Time it throws a larger Error (the one seen in my previous Post).

**Comment by rg-engineering** [comment]
The log gives two hints:

- with "got undefined days" I assume you do not have actual values for json data path (at least for that data call)
- "got 129 channels" gives the hint, that we try to remove old data structure (from version 1.x of daswetter-adapter)

So you could try two things:

- deactivate json data path (just delete URL in adatpter settings)
- disable "delete unused data structure" also in adapter settings

Please do it one by one to see the result. Thanks for your help.

**Comment by BuZZy1337** [comment]
I am facing the same issue...

**Comment by rg-engineering** [comment]
does disabling of "delete unused data structure" also avoid the error on your system?

**Comment by BuZZy1337** [comment]
> does disabling of "delete unused data structure" also avoid the error on your system?

Yes.. After disabling the option everything seems to be fine. :relaxed:

**Comment by GermanBluefox** [comment]
Must be better in 2.7.1: https://github.com/rg-engineering/ioBroker.daswetter/pull/29
