### ISSUE TITLE
Feature request: current weather information in states

### ISSUE THREAD

**Issue by Mic-M** [rg-engineering/ioBroker.daswetter#24]
Hi,

Looks like that "daswetter" does not provide current weather information, but forecast only. 
So users have to use separate scripts [like this](https://forum.iobroker.net/viewtopic.php?t=13207) to be able to get the current weather information into states for visualization.
Suggestion is to provide a state folder "Current" with the information from "daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_x" where "Hour_x" should be the upcoming hour of the current day. 
This would eliminate the need of a separate script and a give us a way easier Vis implementation of the current weather condition.

We know that this is actually not the current measured weather data, but this could be mentioned in the readme, and it really comes close.

Thanks.

**Comment by rg-engineering** [comment]
it's implemented here in branch 2.4.x. Would be great if you could test it ...

**Comment by Mic-M** [comment]
Great, thank you! How can I install the branch 2.4? I have tried to use link "https://github.com/rg-engineering/ioBroker.daswetter/tree/2.4.x" and copied it to ioBroker admin, but it just re-installed 2.3.1.
If I need the console, please let me know the command line. Thanks.

**Comment by rg-engineering** [comment]
I'll merge to master latest on weekend....

**Comment by Mic-M** [comment]
Thank you very much for the implementation!

**Comment by SchiFrank** [comment]
I can't find "current" in the objects. I am using 2.8.0.
![current_missing](https://user-images.githubusercontent.com/50178591/59143089-fdbc8b00-89c7-11e9-83ff-b69dbbe6df8c.PNG)
