### ISSUE TITLE
Hour_24

### ISSUE THREAD

**Issue by Mic-M** [rg-engineering/ioBroker.daswetter#25]
It looks like the states for the first hour of the day are kept in the folder "Hour_24", since folder "Hour_1" starts at "01:00".
Suggestion is to rename "Hour_24" to "Hour_0" to avoid confusion, as "Hour_24" implies that it is the weather information of the day after.

**Comment by rg-engineering** [comment]
can not be done. I just parse received data and don't want to reorder...
![grafik](https://user-images.githubusercontent.com/8238668/80745632-e1b26280-8b20-11ea-9220-309ad4448f68.png)

**Comment by klein0r** [comment]
Do you know what Hour_25 contains?!
Values are different from Hour_24

<img width="1388" alt="Screenshot 2021-04-05 at 14 10 48" src="https://user-images.githubusercontent.com/1959049/113572579-c6958000-9618-11eb-9f84-d4a3591fdba4.png">
