### ISSUE TITLE
Error since last update

### ISSUE THREAD

**Issue by BuZZy1337** [rg-engineering/ioBroker.daswetter#26]
daswetter.0 | 2018-12-11 13:00:36.772 | error | got no data! check data structure...
-- | -- | -- | --

I am getting this error every time the Adapter is pulling fresh data ..
States are being updated successfully without any issues..

**Comment by JoJ123** [comment]
I'm getting the same error message.

**Comment by Mic-M** [comment]
Same here, getting error "got no data! check data structure..." continuously, although paths in adapter settings are working.

**Comment by rg-engineering** [comment]
I guess you use json data path (path 4). If so then this is a known issue also documented already in readme. 
To solve that problem temporarly just use path 3 and do not use path 4 for the moment...

**Comment by Mic-M** [comment]
> I guess you use json data path (path 4). If so then this is a known issue also documented already in readme.
> To solve that problem temporarly just use path 3 and do not use path 4 for the moment...

Exactly, many thanks for the swift feedback. Just removed path 4 and no error message any longer.

Thanks,
Mic

**Comment by rg-engineering** [comment]
I added a auto-repair function to solve that issue. it's not merged to master yet. will be done after testing...
