### ISSUE TITLE
ERROR 11 since version 2.6.0

### ISSUE THREAD

**Issue by Herbert-Testmann** [rg-engineering/ioBroker.daswetter#27]
Error in log file since Update 2.5 -> 2.6

`

host.raspi-3 | 2019-02-03 08:34:10.478 | error | instance system.adapter.daswetter.0 terminated with code 11 (Desired termination)
-- | -- | -- | --
daswetter.0 | 2019-02-03 08:34:10.447 | debug | nothing to do
daswetter.0 | 2019-02-03 08:34:03.341 | debug | update already running
daswetter.0 | 2019-02-03 08:34:03.330 | debug | objects in list: 947
daswetter.0 | 2019-02-03 08:34:03.328 | debug | 5 days forecast done, objects in list 947
daswetter.0 | 2019-02-03 08:34:02.833 | debug | calling forecast 5 days: http://api.daswetter.com/index.php?api_lang=de&localidad=26301&affiliate_id=delete&v=2.0
daswetter.0 | 2019-02-03 08:34:02.829 | debug | using new datastructure
daswetter.0 | 2019-02-03 08:34:02.826 | debug | set timeout to 60 sec
daswetter.0 | 2019-02-03 08:34:02.762 | info | starting. Version 2.6.0 in /opt/iobroker/node_modules/iobroker.daswetter, node: v6.15.1
daswetter.0 | 2019-02-03 08:34:02.667 | debug | statesDB connected
daswetter.0 | 2019-02-03 08:34:02.589 | debug | objectDB connected
host.raspi-3 | 2019-02-03 08:34:00.144 | info | instance system.adapter.daswetter.0 started with pid 25560

`

**Comment by Herbert-Testmann** [comment]
with downgrade to  2.5.0 -> ok


host.raspi-3 | 2019-02-03 09:00:10.292 | info | instance system.adapter.daswetter.0 terminated with code 0 (OK)
-- | -- | -- | --
daswetter.0 | 2019-02-03 09:00:09.057 | debug | system.adapter.admin.0: logging true
daswetter.0 | 2019-02-03 09:00:03.456 | debug | update already running
daswetter.0 | 2019-02-03 09:00:03.444 | debug | objects in list: 947
daswetter.0 | 2019-02-03 09:00:03.443 | debug | 5 days forecast done, objects in list 947
daswetter.0 | 2019-02-03 09:00:02.939 | debug | calling forecast 5 days: http://api.daswetter.com/index.php?api_lang=de&localidad=26301&affiliate_id=delete&v=2.0
daswetter.0 | 2019-02-03 09:00:02.935 | debug | using new datastructure
daswetter.0 | 2019-02-03 09:00:02.932 | debug | set timeout to 60 sec
daswetter.0 | 2019-02-03 09:00:02.868 | info | starting. Version 2.5.0 in /opt/iobroker/node_modules/iobroker.daswetter, node: v6.15.1
daswetter.0 | 2019-02-03 09:00:02.780 | debug | statesDB connected
daswetter.0 | 2019-02-03 09:00:02.676 | debug | objectDB connected
host.raspi-3 | 2019-02-03 09:00:00.124 | info | instance system.adapter.daswetter.0 started with pid 25722

**Comment by Herbert-Testmann** [comment]
I can't say, if all data are updated. 
I can update o 2.6  again and try it a couple of days
js-controller 1.5.3

**Comment by Herbert-Testmann** [comment]
I get new data with 2.6.0  but in log file  Code11

**Comment by Hirsch-DE** [comment]
Ich habe das selbe Problem. Alles die gleichen Voraussetzungen.

**Comment by GermanBluefox** [comment]
It is not the error, but just information that adapter wanted to be terminated. In js-controller 1.5.7 the severity was changed to "info" from "error"

**Comment by Steff42** [comment]
Bei mir kommt statt Error eine Warnung. DasWetter Version 2.7.2. JS-Controller 1.5.7.
![image](https://user-images.githubusercontent.com/35137293/52912534-ef305380-32b2-11e9-89c9-884d7b92ab52.png)

**Comment by wendy2702** [comment]
Ich habe das auch mit Das Wetter 2.7.3 und JS 1.5.7.

![image](https://user-images.githubusercontent.com/33424168/54124712-70d35700-4403-11e9-9f24-a7cc10921a83.png)

**Comment by Maja61** [comment]
i have the same problem with 2.7.3 an JS 1.5.7, see [https://forum.iobroker.net/topic/20854/terminated-warn-11-vom-daswetter-adapter/2](url)

**Comment by rg-engineering** [comment]
I changed exit code 11 to 0 now

**Comment by Steff42** [comment]
Looks good now!
I installed from GH a few hours ago and the warning comes up no more.
Thanks Steffen
