### ISSUE TITLE
values are datype string -> do not work in flot

### ISSUE THREAD

**Issue by passuff** [rg-engineering/ioBroker.daswetter#28]
I tried to visualize cloud values [%] in flot without success until I recognized its string. I now solved it by rewritung all cloud values from string to int by script. I hope someone can change the data type in the adapter.

**Comment by GermanBluefox** [comment]
Will be changed in next version: https://github.com/rg-engineering/ioBroker.daswetter/pull/29/files#diff-7a9076d6d94e62c13d641aa71f19ae8eR1917

**Comment by passuff** [comment]
Currently I'm using 2.7.2 but values are still type string. I thought it will be fixed in 2.7.0, or did I get it wrong?

**Comment by rg-engineering** [comment]
will release a 2.7.3 soon...

**Comment by rg-engineering** [comment]
2.7.3 is now on latest repo for iobroker on NPM. Would be gret if you could test it (@passuff )

**Comment by passuff** [comment]
Its working now. thx
