### ISSUE TITLE
Does this adapter work?

### ISSUE THREAD

**Issue by GermanBluefox** [rg-engineering/ioBroker.daswetter#3]
May be include it into repositories?

**Comment by rg-engineering** [comment]
The adapter works well from my point of view. I don't have open issues or complains...
So why not to include in repsoitories but how? What can/should I do?

**Comment by GermanBluefox** [comment]
Just make pull request against https://github.com/ioBroker/ioBroker.repositories and add your adapter.
What is required: tests, readme.md, short description in io-package.json.

**Comment by rg-engineering** [comment]
will do so later. Got some feedback... but prepared already...
