### ISSUE TITLE
actual version 2.6.1 not in default 

### ISSUE THREAD

**Issue by Seqway** [rg-engineering/ioBroker.daswetter#30]
Hello,
If i look into IoBroker the last version i get is 2.5.0 but i see the actual one is 2.6.1

Maybe you didn't share it ?
My storage is on DEFAULT and not on LATEST

**Comment by rg-engineering** [comment]
2.6.1. is in latest repo already, but not declared as "stable". So it's not available in default repo yet. I still have a pull request to be checked and then I will release 2.7.x
