### ISSUE TITLE
Icons Pfad geändert?

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.daswetter#31]
Hallo,
ich glaube der Pfad zu den Icons wurde geändert?

Sigi

**Comment by rg-engineering** [comment]
ja, ich habe die Icons von DasWetter übernommen. Dort gibt es für Galerie 5 jetzt svg und png Icons und die auch noch in weiß oder farbig. Das wurde mit 2.6.0 eingeführt...

**Comment by sigi2345** [comment]
Hm... Wo und wie kann ich jetzt den Pfad ändern?

![Screenshot (2475)](https://user-images.githubusercontent.com/41079106/54685787-f6e45180-4b17-11e9-97fc-72c52cba763d.png)

**Comment by sigi2345** [comment]
Hab es hinbekommen.......

**Comment by rg-engineering** [comment]
In der aktuellen Version 2.8.0 kann man den Pfad im admin auswählen oder manuell eintragen...
