### ISSUE TITLE
Use custom icons / icon folder

### ISSUE THREAD

**Issue by Maja61** [rg-engineering/ioBroker.daswetter#33]
please create a possibility to use custom-icons in a custom path/folder. 

For Android Vis-App it is necessary to store the icons in the related folder of the project, otherwise the icons will not synchronized to the tablet.

**Comment by rg-engineering** [comment]
Are you locking for a new setting parameter to set the necessary path in admin? Then this path should be used in the same way as I do for different galeries right now? Is this right?

**Comment by Maja61** [comment]
i just want to locate the icons in the vis.0 folder, for example:
http://ip:8082/vis.0/main/icons/tiempo-weather/galeria1/1.png or
vis.0/main/icons/tiempo-weather/galeria1/1.png

and therefore will be nice to have a possibility to set a userspecific path in the config mask.

**Comment by rg-engineering** [comment]
@Maja61 can you please check latest commit here and verify it solves your feature request?

**Comment by Maja61** [comment]
Thanks, thats what i need! But the preview icons should have the port 8082, now the port is set to 8081 thats why i dont get a preview. 
![Wetter](https://user-images.githubusercontent.com/33453078/54555734-91794f00-49b7-11e9-9b73-37c1a33e9678.png)
