### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by foxriver76** [rg-engineering/ioBroker.daswetter#353]
Please Release a new Version with current GitHub Content or even better allow the Adapter Core Dependency to get automatically Updated in the Same Major Release by specifying it with ^3.1.4 instead of a fixed version. This prevents from such scenarios in the future.

see also https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/560

**Comment by rg-engineering** [comment]
done with 3.1.14
