### ISSUE TITLE
why "NextHour2" in path

### ISSUE THREAD

**Issue by truegreyhound** [rg-engineering/ioBroker.daswetter#36]
I don't understand the meaning of  "NextHours2" in the data-path "daswetter.0.NextHours2.Location_1.Day_N".  I use the new datastructer and I think, a data path like "daswetter>.<instance>.Location_<#>.xxx is more plausible.

**Comment by rg-engineering** [comment]
DasWetter delivers three different version of data (see Metadata_de.pdf). The adapter just parses all three versions and provide the data to be used by users. So every user is free to use only one path or a combination of more then one. If I would merge some data than other users would miss exactly that...
