### ISSUE TITLE
Einbindung HD und Mond Bilder

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.daswetter#37]
Hallo,

vielleicht kann man diese Bilder im Adapter fix integrieren?

https://forum.iobroker.net/topic/20675/projekt-wetterview-von-sigi234/51

**Comment by rg-engineering** [comment]
dafür hatte ich ja den "custom"-Pfad in den settings eingebaut. Bilder einfach irgendwohin legen und in den settings vom adapter den Pfad einstellen. Der Adpter liefert dann die ganze Adresse zu den jeweiligen Bild, und das muss dann nur noch auf das vis-Image Objekt gelegt werden...
Aber ja, ich könnte zusätzlich zu den Icons von DasWetter weitere hinzufügen. Die werden dann aber eben von allen usern mitinstalliert, auch die, die es nicht benötigen...

**Comment by sigi2345** [comment]
Hallo, ja das mit custom kenne ich, aber dann verstehe ich das nicht:
Der benutzerdefinierte Pfad muss das Format "/ adapter / daswetter / icons / tiempo-weather / galeria4 /" haben. 
Ist das dann nicht egal wohin in Vis.0 ich die Icons speichere?

**Comment by rg-engineering** [comment]
Du kennst die Datenpunkte IconURL, MoonIconURL und WindIconURL? Dort kommt der Pfad + Icon-Nr. + Erweiterung heraus. Das ganze lege ich auf "Object ID" eines "basic string image src" im vis. 
Mit dem benutzerdefinierte Pfad kann man zusätzlich auf irgendeinen erreichbaren Pfad verweisen, der die eigenen Icons enthält
![grafik](https://user-images.githubusercontent.com/8238668/55502371-b4a92d00-564c-11e9-8320-b56cdf20f79c.png)
Die Übersetzungstabelle aus deiner vis ist im adpater schon vorhanden.
In deinem Fall einfach /vis.0/WetterIcons/WetterHD/ in den benutzdefinierten Pfad eingeben. Und als ObjectId wie im Bild den Wert verwenden.

**Comment by sigi2345** [comment]
Danke, ist jetzt klar ich habe das Widget basic Image 8 genommen.........
Geht jetzt, es dauert eine Weile bis die custum Daten übernommen werden..

Kann geschlossen werden........
