### ISSUE TITLE
Error: force terminate, objects still in list: 107

### ISSUE THREAD

**Issue by Steff42** [rg-engineering/ioBroker.daswetter#38]
Hallo,
seit gestern Nachmittag bekomme ich die Fehlermeldung force terminate, objects still in list: 107.
Ab und zu steht am Ende der Meldung auch statt der 107 nur eine 0.
Fehler taucht seit 09.04. ca. 15:30Uhr alle paar Stunden einmal auf, Daten scheinen aber aktualisiert worden zu sein. Der Adapter beendet sich im Anschluss regulär mit Code 11. Siehe auch Screenshot vom Log:
![image](https://user-images.githubusercontent.com/35137293/55901572-e03a9300-5bc9-11e9-9be2-1d2d447fd81f.png)

Ich habe die Version 2.8.0 installiert.
Gruß Steffen

**Comment by rg-engineering** [comment]
Wenn der Adapter mit objects still in list: größer als 0 abbricht, reicht die Zeit zum download und parsen nicht aus. Dafür gibt es den timeout-Wert im admin des Adapters. Standard sind 60 Sekunden eingestellt.. Die sind im vorliegenden Beispiel auch im log sichtbar. Ich würde den Timeout einfach um 10 Sekunden verlängern. Wenn dann immer noch Meldungen mit "force terminate" auftauchen, würde ich ein debug-log benötigen, um den Fehler zu analysieren...

**Comment by Steff42** [comment]
OK, vielen Dank für die Rückmeldung, werde ich mal versuchen. Komischerweise taucht die Fehlermeldung seit gestern nicht mehr auf.
Da das Problem somit für mich gelöst ist mache ich hier zu.
Danke nochmals für die Info!
Gruß Steffen
