### ISSUE TITLE
Current Day instead of Current Hour

### ISSUE THREAD

**Issue by siggi85** [rg-engineering/ioBroker.daswetter#39]
It would be very helpful if the current values get their own "day" structure instead of just have "one hour" in Day_1. So that we not just have "current" value, but additionally the values für "in one hour" "in two hours" and so on. Maybe for the next 12 Hours or configurable in adapter config?!
This would make things possible like "IF temperature reches a limit AND the temperature will still go higher the next hour THEN do blind on 100%". So that the blinds just go down when the temperature will increase.

**Comment by rg-engineering** [comment]
@siggi85  is this request still valid?

**Comment by siggi85** [comment]
In the meantime I made a script which is determine the next hour values but it would be still helpful and would made the script easier.
