### ISSUE TITLE
remove and to many events

### ISSUE THREAD

**Issue by MeisterTR** [rg-engineering/ioBroker.daswetter#4]
when i use 5-day and hourly wether, the admin say that there are too many events in the last 3 seconds. And when i remove the hourly weather its all fine, but then the objects are still there

**Comment by rg-engineering** [comment]
@MeisterTR   The second is true: I do not remove any object when configuration is changed. But you can remove it manually. For the first: do you have any log to show the behavior? Where do you see that message from admin?
