### ISSUE TITLE
No new registration possible at www.daswetter.com

### ISSUE THREAD

**Issue by mcm1957** [rg-engineering/ioBroker.daswetter#408]
Looks like that at least currently NO REGISTRATION for new users is possible.

The (deep) Link mentioned at README.md still exists but does no longer seem to work. The rgistration link at the official start page is no longer present,

See: https://forum.iobroker.net/topic/59111/problem-anmeldung-registrierung-bei-daswetter-com/62

**I would suggest to add a remark at README:md** until the situation is fixed (or the adapter must be deprectated due to deprecation of official api).

**Comment by rg-engineering** [comment]
hint added with 3.2.2
