### ISSUE TITLE
Feature-Requests: Regenwahrscheinlichkeit

### ISSUE THREAD

**Issue by Bluelightcrew** [rg-engineering/ioBroker.daswetter#42]
Auf der Homepage von das Wetter gibts zumindest für den heutigen tag die Regenwahrscheinlichkeit in % , da sollte es doch auch möglich sein das in den Iobroker zu integrieren.

**Comment by rg-engineering** [comment]
Die api liefert den Wert leider nicht. Das kann man selbst prüfen, indem man die URL aus den Einstellungen direkt in die Adresszeile eines browsers eingibt.

**Comment by Bluelightcrew** [comment]
Oh OK das wusste ich nicht, dachte das wird da auch ausgegeben, da es ja auf der Seite auch sichtbar ist.
Dann kann man hier zu machen

**Comment by sigi2345** [comment]
> Oh OK das wusste ich nicht, dachte das wird da auch ausgegeben, da es ja auf der Seite auch sichtbar ist.
> Dann kann man hier zu machen

Es gibt andere Adapter die das können..........

**Comment by Snapergy** [comment]
Ich habe einmal bei dasWetter angefragt, ob die Regenwahrscheinlichkeit mit in die XML-Datei aufgenommen werden kann. Sollte ich eine Antwort erhalten, werde ich diese hier angeben.

**Comment by Snapergy** [comment]
Das war die Antwort auf meine Anfrage

> Guten Abend, 
> 
> vielen Dank für Ihre Mail. Es freut uns, dass Sie unsere Dienste nutzen. Die Regewahrscheinlichkeit bieten wir derzeit leider nicht in der API an. Wir nehmen Ihren Wunsch aber gerne auf und hoffen dies in dem nächsten Update unterzubekommen. 
> 
> Besten Dank und viele Grüße
> das Team von daswetter.com
