### ISSUE TITLE
Show Moon Icons after Sunset

### ISSUE THREAD

**Issue by Ahrenfelde** [rg-engineering/ioBroker.daswetter#43]
Hi,

it would be nice to show the Moon Icon after Sunset in the Currect.iconURL section.
So it is possible to build a current weather display in vis.

----
Es währe super wenn der Adapter das Mond Symbol unter Current.iconURL anzeigen würde.
Aktuell ist es so, dass auch Nachts eine Sonne angezeigt wird. 
Mit dem Mond nach dem Sonnenuntergang wäre es leichter eine Anzeige des Aktuellen Wetters im Vis zu realisieren.
Grüße
Jan

**Comment by rg-engineering** [comment]
Kannst du das etwas genauer beschreiben? Es existieren doch gar keine Icons für Wetter mit Mond. Ich könnte mir nur vorstellen, dass über customs zu lösen?

**Comment by ds-1982** [comment]
Hat sich bezüglich der Symbole nach Sonnenuntergang schon eine Lösung ergeben?
Auf der Website werden Symbole mit Mond dargestellt. Aber die API scheint diese Symbole nicht zu unterstützen.

Ausschnitt von daswetter.com
![image](https://user-images.githubusercontent.com/74044795/98811634-70356400-2421-11eb-8729-ca91a8c011d0.png)

**Comment by rg-engineering** [comment]
Die webseite und die API sind unterschiedlich. Ich kann nur die Icons anbeiten, die in der API zur Verfügung stehen...
