### ISSUE TITLE
not all object are shown

### ISSUE THREAD

**Issue by Koalabaer** [rg-engineering/ioBroker.daswetter#57]
Hello,

ive installed the latest version 2.8.1 (npm 6.12.0, node 12.13.0) and put in two links for the configuration for the next 7 days and detailed hourly of the next five days. In the objects it shows me the next 7 days and the next five days hourly. But on day3, 4 and 5 on the hourly it shows only the hours from 1 to 8, not the rest from 9 to 24 as in day 1 and 2...

Someone can help please?

BR

Gerrit

**Comment by rg-engineering** [comment]
that's the standard behavior. DasWetter provides data for day 3, 4 and 5 with different time difference than day 1 and 2. You can see it in datapoint 

> daswetter.0.NextHours.Location_1.Day_5.Hour_1.hour_value

you also can verify it if you just use the URL in any browser.
