### ISSUE TITLE
Icon 9.png missing

### ISSUE THREAD

**Issue by BA2000** [rg-engineering/ioBroker.daswetter#59]
hi, it seems to me that the icon 9.png in galeria1 - icons/viento-wind/galeria1/9.png   is missing.

greetings

**Comment by rg-engineering** [comment]
I downloaded icons from DasWetter.com:
![grafik](https://user-images.githubusercontent.com/8238668/86822132-83a77b80-c08b-11ea-84bf-2e31db51a0eb.png)

and there is no icon 9.png

![grafik](https://user-images.githubusercontent.com/8238668/86822042-670b4380-c08b-11ea-8fc2-ab08f2c3bd3e.png)
