### ISSUE TITLE
Exception in 5DaysForecast

### ISSUE THREAD

**Issue by daniel-lo** [rg-engineering/ioBroker.daswetter#61]
Hallo, habe diesen Fehler im Log:

 (3262) exception in 5DaysForecast [Error: getaddrinfo EAI_AGAIN api.daswetter.com api.daswetter.com:80]

**Comment by rg-engineering** [comment]
Bitte auf deug-level umschalten und das log posten. Ich brauche dazu mehr Informationen...

**Comment by daniel-lo** [comment]
hab ich gemacht .. heute alleridngs kein Fehler .. vielleicht war das Internet auch nur gestört?!
