### ISSUE TITLE
I can't get the adapter to work

### ISSUE THREAD

**Issue by copperfield74** [rg-engineering/ioBroker.daswetter#62]
Hi, I've installed version 2.8.1 but after making the configuration there was no "indicator light" infront of the adapter. I tried to downgrade to 2.8.0 but still the same problem. So there are no daswetter.0 within Objects. Of course I restarted IOBroker several times. Any ideas?
![grafik](https://user-images.githubusercontent.com/62651258/84550150-17469000-ad0a-11ea-8f59-002961bc72b2.png)
![grafik](https://user-images.githubusercontent.com/62651258/84550271-6db3ce80-ad0a-11ea-8d3f-6f2579578b02.png)

**Comment by rg-engineering** [comment]
keep in mind, this is a scheduled adapter. such adapters does not have the light indicator beside the instance name. so thats okay. your log is showing that adapter is running well: it's calling the data but then the log stops. so from my point of view what you show here is okay and bug free...
I suggest  to wait again until adapter runs and then post the complete debug log (but please as text not as a picture) you can download the log from \opt\iobroker\log

**Comment by copperfield74** [comment]
Hi, here is my log! Still no Objects in Iobroker. I hope it's okay that I only included daswetter logs. If you need more please let me know.
[daswetter.log](https://github.com/rg-engineering/ioBroker.daswetter/files/4775204/daswetter.log)

**Comment by rg-engineering** [comment]
okay, got it.. I just updated stable repo with 3.0.1 of the adapter. please use that version, should solve your problem. the problem is, that for some reasons you do not get an answer on your request for  forecast hourly.

**Comment by copperfield74** [comment]
@rg-engineering Thanks very much! Problem solved. Highly appreciated.
