### ISSUE TITLE
daswetter parsing fails

### ISSUE THREAD

**Issue by mplogas** [rg-engineering/ioBroker.daswetter#65]
**Description:** daswetter parsing stopped working somewhere between July, 8th and 9th 

**expected result** daswetter parses incoming data correctly

**System** 
+ Debian Buster x64, latest
+ Node 10.21
+ ioBroker Js 3.1.6
+ daswetter 3.0.1

**steps to reproduce**
1. get rid of all daswetter instances and also delete them
2. get the latest one from GitHub (or the current stable, doesn't matter)
3. set up daswetter Adapter, use any feed (I preferred the JSON feed, but I also tried with different feeds for different cities) and some random minutes to fire the CRON in order to avoid the server hugging.
4. receive following log message (info)
```
host.iobroker | 2020-07-10 09:34:01.895 | info | instance system.adapter.daswetter.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
daswetter.0 | 2020-07-10 09:34:01.379 | info | (32234) Terminated (NO_ERROR): Without reason
daswetter.0 | 2020-07-10 09:34:00.614 | info | (32234) got wrong data structure! trying to repair...
daswetter.0 | 2020-07-10 09:34:00.474 | info | (32234) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.daswetter, node: v10.21.0, js-controller: 3.1.6
```

debug just tells me that the parsed values are NULL, no further info available.

**Comment by rg-engineering** [comment]
please poste debug log anyway, because info log looks good. are you shure you use correct url in adapter settings? (I had such a case already a couple of days ago here in issue list...)

**Comment by mplogas** [comment]
Sure. 

**API used:** http://api.daswetter.com/index.php?api_lang=de&localidad=26301&affiliate_id=4e1m9hc4tosx&v=3.0 (yields result according to Postman)

![grafik](https://user-images.githubusercontent.com/842121/87140017-1a995100-c2a1-11ea-8038-c11efb845f9d.png)

Log: see attached file

**Comment by mplogas** [comment]
> are you shure you use correct url in adapter settings

I assume so, as it worked before.

**Comment by rg-engineering** [comment]
can you describe why you think parser does not work well? The log looks pretty nice, everything is okay there. The "null" in log is as expected, because no new object is added. I assume a value different to null only, when a new entry should be added. This is not the case, so null is perfect

**Comment by mplogas** [comment]
> can you describe why you think parser does not work well?

Because it stopped updating the datapoints / objects. I only realized because I compared openweather vs daswetter as dataproviders in the lovelace UI and realized daswetter was still stuck on Wednesday while openweather correctly displayed Thursday weather.

**Comment by rg-engineering** [comment]
You said you reinstalled the adapter. Did you also delete all objects? If so, does the adapter create all objects the next time it is started? If you put the mouse on the object value, what time stamp is shown there?

**Comment by nachtschatt3n** [comment]
I have the same problem and I reinstalled without success

**Comment by rg-engineering** [comment]
@nachtschatt3n can you please also answer my last question in my post above? A debug log would also be nice...

**Comment by mplogas** [comment]
Hi @rg-engineering 
sorry for my late reply: yes, I did remove all objects and and they were recreated. I'm afraid I can't provide any further help here, as I have moved away from iobroker entirely soon after.

**Comment by rg-engineering** [comment]
@nachtschatt3n do you have more information? or can I close this issue now?

**Comment by rg-engineering** [comment]
no further info -> closed
