### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by andremueller83** [rg-engineering/ioBroker.daswetter#67]
Hallo in die Runde,
was gebe ich denn bei der Registrierung auf

https://www.daswetter.com/api/#/anmeldung

als Internetseite ein?

Ich betreibe keine Website und möchte die Daten nur für den privaten Gebrauch nutzen.

Viele Grüße 
André

**Comment by rg-engineering** [comment]
suche bitte danach im Forum, diese Frage wird alle halbe Jahre neu gestellt:
https://forum.iobroker.net/topic/5347/adapter-daswetter

**Comment by Jaaannis** [comment]
http://localhost.de
