### ISSUE TITLE
Too many debug entries

### ISSUE THREAD

**Issue by Koalabaer** [rg-engineering/ioBroker.daswetter#68]
Hi,

is it possible to reduce the debug entries? 

my log files are full of daswetter entries every 15 minutes and it took long to download them and so on... 

would it be possible to deactivate the logging for the daswetter adapter or reduce it to a minimum of errors or something like that?

BR and thanks

Koala

**Comment by rg-engineering** [comment]
then just disable debug logs. 

![grafik](https://user-images.githubusercontent.com/8238668/93244004-5103b880-f789-11ea-908b-c88ae691c338.png)


on the other side: why do you run it every 15 minutes?

**Comment by Koalabaer** [comment]
Thanks worked for me ;)
