### ISSUE TITLE
Nach Update auf Version 3.0.2 wird das Objekt wind_dir nicht mehr "gefüllt"

### ISSUE THREAD

**Issue by Steff42** [rg-engineering/ioBroker.daswetter#69]
Hallo,
habe heute das Update auf die 3.0.2 gemacht und danach festgestellt, das das Objekt wind_dir nicht mehr "gefüllt" wird. Ich hatte dies bemerkt, weil ich mit einem Alias aus der Windrichtung E(east) ein O(st) mache und der Alias seit dem Update einen Fehler wirft.
Hier der Fehler, der ausgegeben wird.
![image](https://user-images.githubusercontent.com/35137293/93616707-5e14e780-f9d5-11ea-817c-d2681b46ab35.png)
Ein Downgrade auf die 3.0.1 und das Objekt wird wieder "gefüllt".
Hier ein Screenshot wie es sein soll (bei V 3.0.2 bleibt der rote Kringel also das Feld komplett leer.
![image](https://user-images.githubusercontent.com/35137293/93616974-b350f900-f9d5-11ea-8b79-fb41a8241b16.png)

Gruß Steffen

**Comment by rg-engineering** [comment]
ja, danke. ich sehe das jetzt auch. schaue ich mir an...

**Comment by Steff42** [comment]
Moin,
mit der 3.0.3 passt das wieder.

Danke!
