### ISSUE TITLE
Error "got wrong data structure! trying to repair..."

### ISSUE THREAD

**Issue by cherberg** [rg-engineering/ioBroker.daswetter#74]
On a freshly installed iobroker system (on RPI4) I am getting the below errors in the logs every 15 minutes:

```
host.raspberrypi | 2020-10-09 13:00:13.791 | info | instance system.adapter.daswetter.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
daswetter.0 | 2020-10-09 13:00:13.259 | info | (7753) Terminated (NO_ERROR): Without reason
daswetter.0 | 2020-10-09 13:00:10.685 | info | (7753) got wrong data structure! trying to repair...
daswetter.0 | 2020-10-09 13:00:01.279 | info | (7753) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.daswetter, node: v10.22.0, js-controller: 3.1.6
host.raspberrypi | 2020-10-09 13:00:00.019 | info | instance system.adapter.daswetter.0 started with pid 7753
```

**Comment by rg-engineering** [comment]
There is no error, we see only info messages! Everything works well...
The info about wrong data structure is just to inform, that we still get data from server which are different to their own specification. The adapter can and do handle that. so no problem here...

**Comment by cherberg** [comment]
Well I still believe a continous termination and restart of the add-in to be an error although the log just informs about this.

**Comment by rg-engineering** [comment]
this is a scheduled adapter which only runs on certain times. So it starts at the time you've configured in settings and it will terminate istself. you can and should configure it to run only once per a hour or less... so still no bug here (and by the way the original bug report was not clear about restart, it ws reported you see some unclear error messages...)
