### ISSUE TITLE
better rain values

### ISSUE THREAD

**Issue by Elvissimo** [rg-engineering/ioBroker.daswetter#76]
Hi, actually the adapter shows only e.g. 1mm or 2mm of rain expected in hour xy. It would be great to get a better resolution and one decimal place added. So values like 0.3mm, 0.9mm or 1.4mm could be seen.
It is seldom that more than 1mm rain occurs during one hour, but often smaller amounts are expected. At the moment it looks like DasWetter shows e.g. 8mm rain for today, but all hourly values are just 0mm (originally at their website they show up as 0.5 or 0.8mm and sum up to 8mm in total). I mean these values: daswetter.0.NextHours.Location_1.Day_1.Hour_1.rain_value
Thank you!

**Comment by derelvis** [comment]
Hi there
fully support this! 
I even would say it is more of a bug than an enhancement ;-)

Value from used xml file:
![image](https://user-images.githubusercontent.com/17635497/96250052-85e47480-0fae-11eb-8284-d1acf30ba95e.png)

Value within ioBroker DasWetter adapter:
![image](https://user-images.githubusercontent.com/17635497/96250116-a0b6e900-0fae-11eb-96e1-6864896ab0a8.png)

I found this german thread regarding the issue: https://forum.iobroker.net/topic/37501/daswetter-adapter-zeigt-regen-0mm

DasWetter version 3.0.3

**Comment by Elvissimo** [comment]
The german thread is mine ;-) 
I first thought it‘s just my fault again and I did something wrong in ioBroker somewhere...

**Comment by Elvissimo** [comment]
Hat super funktioniert, vielen Dank für die schnelle Überarbeitung!

**Comment by derelvis** [comment]
Wow Dude, that was fast :-D Thanks a lot!

Too many Elvises here ;-) :-D
