### ISSUE TITLE
Problem mit deinem adapter

### ISSUE THREAD

**Issue by eXplOiD1** [rg-engineering/ioBroker.daswetter#8]
Guten Tag,
ich habe ein Problem mit deinem Adapter er liest nichts von der seite aus
den fehler den ich im log bekomme ist folgender.

host.homeserver | 2017-12-26 16:18:06.623 | info | instance system.adapter.daswetter.0 terminated with code 0 (OK)
-- | -- | -- | --
daswetter.0 | 2017-12-26 16:18:06.614 | debug | cleaned everything up...
daswetter.0 | 2017-12-26 16:18:01.416 | error | exception in 7DaysForecast [TypeError: Cannot read property 'report' of undefined]
daswetter.0 | 2017-12-26 16:18:00.627 | debug | calling forecast: http://www.daswetter.com/wetter_Merzig-Europa-Deutschland-Saarland--1-27038.html
daswetter.0 | 2017-12-26 16:18:00.627 | info | starting. Version 1.0.0 in /mnt/iobroker/node_modules/iobroker.daswetter, node: v8.8.0
host.homeserver | 2017-12-26 16:18:00.014 | info | instance system.adapter.daswetter.0 started with pid 26664
host.homeserver | 2017-12-26 16:17:06.629 | info | instance system.adapter.daswetter.0 terminated with code 0 (OK)
daswetter.0 | 2017-12-26 16:17:06.624 | debug | cleaned everything up...

**Comment by rg-engineering** [comment]
Hallo, die URL [http://www.daswetter.com/wetter_Merzig-Europa-Deutschland-Saarland--1-27038.html] ist nicht richtig. Die muss so ähnlich aussehen: URL [http://api.daswetter.com/index.php?api_lang=de&localidad=xxxx]. Die richtige URL bekommst du, wenn du dich unter URL [ http://api.daswetter.com/ ] registrierst.

**Comment by eXplOiD1** [comment]
ok danke hat geklappt

**Comment by l3d00m** [comment]
@rg-engineering Moin, könntest du die URL in der Readme verlinken? Ich habe die auch nur durch dieses Issue gefunden
