### ISSUE TITLE
Fehler exception in getForecastDataHourlyJSON [Error: getaddrinfo EAI_AGAIN api.daswetter.com]

### ISSUE THREAD

**Issue by TepMan** [rg-engineering/ioBroker.daswetter#90]
Hi,

seit letzter Nacht wirft der Adapetr den o. g. Fehler:

`

```
daswetter.0 | 2021-04-22 17:10:01.811 | info | (15022) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
daswetter.0 | 2021-04-22 17:10:01.810 | debug | (15022) Plugin sentry destroyed
daswetter.0 | 2021-04-22 17:10:01.809 | debug | (15022) timer killed
daswetter.0 | 2021-04-22 17:10:01.809 | debug | (15022) exit, all done
daswetter.0 | 2021-04-22 17:10:01.808 | error | (15022) exception in getForecastDataHourlyJSON [Error: getaddrinfo EAI_AGAIN api.daswetter.com]
daswetter.0 | 2021-04-22 17:10:01.778 | debug | (15022) calling forecast hourly JSON: http://api.daswetter.com/index.php?api_lang=de&localidad=96242&affiliate_id=ENTFERNT&v=3.0
daswetter.0 | 2021-04-22 17:10:01.771 | debug | (15022) set timeout to 120 sec
daswetter.0 | 2021-04-22 17:10:01.744 | info | (15022) starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.daswetter, node: v12.22.1, js-controller: 3.2.16
daswetter.0 | 2021-04-22 17:10:01.512 | debug | (15022) Plugin sentry Initialize Plugin (enabled=true)

```
`

Folgendes habe ich schon versucht:

- Von XML auf JSON gewechselt und umgekehrt
- API-URL direkt aufgerufen, geht, sowohl mit XML und JSON, Daten sehen erstmal ok aus
- ioBroker durchgestartet
- ioBroker aktualisiert
- den ganzen Raspi durchgestartet

Adapter 3.0.4
JS-Controller 3.2.16
NodeJS 12.22.1 

Im Anhang sind die Wetterdaten von der API als JSON und XML.

[Wetterdaten.zip](https://github.com/rg-engineering/ioBroker.daswetter/files/6359403/Wetterdaten.zip)

**Comment by rg-engineering** [comment]
Das sieht mir nach einem Netzwerk / Proxy / DNS Problem aus. Hat das System (Raspi) Zugang zum Internet und ist die URL von dort erreichbar?

**Comment by TepMan** [comment]
Ja, URL ist auch vom Raspi direkt erreichbar, sowohl vom Desktop mit Chrome als auch per wget. Hatte auch erst meine DNS-Settings in Verdacht, aber alles andere funktioniert.

**Comment by TepMan** [comment]
Hi, ich weiß nicht warum, aber seit heute Vormittag läuft es scheinbar wieder. Habe nichts weiter geändert, nur die Instanz vom Adapter lag über Nacht tot. Vorhin mal testweise angeworfen und geht wieder. Ich mach das Issue zu. Danke.
