### ISSUE TITLE
Update js-controllers V 3.3.1 Warnmeldungen

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.daswetter#91]
Hallo,

nach einen Update des js-controllers auf V 3.3.1 kommen folgende Warnmeldungen:

```
daswetter.0 | 2021-04-30 06:37:11.939 | info | (16648) cleaned everything up...
daswetter.0 | 2021-04-30 06:37:11.416 | info | (16648) Terminated (NO_ERROR): Without reason
daswetter.0 | 2021-04-30 06:37:11.108 | warn | (16648) State value to set for "daswetter.0.NextHours2.Location_1.Day_5.local_time_offset" has wrong type "number" but has to be "string"
daswetter.0 | 2021-04-30 06:37:10.698 | warn | (16648) State value to set for "daswetter.0.NextHours2.Location_1.Day_4.local_time_offset" has wrong type "number" but has to be "string"
daswetter.0 | 2021-04-30 06:37:10.306 | warn | (16648) State value to set for "daswetter.0.NextHours2.Location_1.Day_3.local_time_offset" has wrong type "number" but has to be "string"
daswetter.0 | 2021-04-30 06:37:09.908 | warn | (16648) State value to set for "daswetter.0.NextHours2.Location_1.Day_2.local_time_offset" has wrong type "number" but has to be "string"
daswetter.0 | 2021-04-30 06:37:09.474 | warn | (16648) State value to set for "daswetter.0.NextHours2.Location_1.Day_1.local_time_offset" has wrong type "number" but has to be "string"
daswetter.0 | 2021-04-30 06:37:09.414 | info | (16648) got wrong data structure! trying to repair...
daswetter.0 | 2021-04-30 06:37:01.233 | info | (16648) starting. Version 3.0.5 in C:/Program Files/iobroker/Home/node_modules/iobroker.daswetter, node: v12.22.1, js-controller: 3.3.1
```

**Comment by rg-engineering** [comment]
Warnungen wurden mit 3.0.6 beseitigt...

**Comment by sigi2345** [comment]
> Warnungen wurden mit 3.0.6 beseitigt...

Läuft, Danke. Kann geschlossen werden.

**Comment by rg-engineering** [comment]
Die Meldungen sollten einmalig kommen. Das sind die notwendigen Anpassungen in den Datenpunkten... Beim zweiten Lauf sollten solche Meldungen nicht mehr erscheinen...

**Comment by sigi2345** [comment]
> Die Meldungen sollten einmalig kommen. Das sind die notwendigen Anpassungen in den Datenpunkten... Beim zweiten Lauf sollten solche Meldungen nicht mehr erscheinen...

Jupp, geht jetzt. Keine Meldungen mehr.
Kann man schließen. Danke.

**Comment by sigi2345** [comment]
Sorry, kommt wieder

![Screenshot (3761)](https://user-images.githubusercontent.com/41079106/116820122-9edffc00-ab73-11eb-961a-c05b9c1b17a9.png)

**Comment by rg-engineering** [comment]
Ich sehe keinen Grund, warum das passieren sollte... seltsam.
Ich hole mir das Objekt, prüfe ob es das enthält, was ich erwarte und falls nicht, ändere ich das Objekt. Das sollte einmalig passieren, danach sollte das Objekt ja so bleiben...
Kannst du mal vom github hier installieren? Habe das log mal erweitert. Ich hoffe zu sehen, welcher Eintrag im Objekt unterschiedlich ist...

**Comment by sigi2345** [comment]
> Ich sehe keinen Grund, warum das passieren sollte... seltsam.
> Ich hole mir das Objekt, prüfe ob es das enthält, was ich erwarte und falls nicht, ändere ich das Objekt. Das sollte einmalig passieren, danach sollte das Objekt ja so bleiben...
> Kannst du mal vom github hier installieren? Habe das log mal erweitert. Ich hoffe zu sehen, welcher Eintrag im Objekt unterschiedlich ist...

Erledigt, brauchst du was?

**Comment by rg-engineering** [comment]
wenn die Warnungen wieder auftauchen hätte ich gern das log...

**Comment by sigi2345** [comment]
> wenn die Warnungen wieder auftauchen hätte ich gern das log...

[DasWetter_debug.txt](https://github.com/rg-engineering/ioBroker.daswetter/files/6411994/DasWetter_debug.txt)

**Comment by BramTown** [comment]
Danke dir für die schnelle Anpassung

**Comment by Diginix** [comment]
@rg-engineering 
Im issue #93 ist aber nicht JS-Controller 3.3.x sondern 3.2.16 im Einsatz. Entweder ist dessen Ver. egal oder es sind differenzierte Probleme.

**Comment by rg-engineering** [comment]
@Diginix das "neue" Verhalten ist eine Folge aus den ersten Änderungen hier...

**Comment by rg-engineering** [comment]
@sigi2345 @Diginix könnt ihr nochmal die Version hier aus github installieren? Fehler sollte jetzt behoben sein...

**Comment by Feuer-sturm** [comment]
@rg-engineering Ich hab auch gerade einmal die github version installiert und aktuell sind keine Meldungen mehr vorhanden. Ich habe ioBroker auch einmal neu gestartet und alles von daswetter.0 war ruhig.

js-controller 3.3.7
daswetter 3.0.7 (aus github)

**Comment by Diginix** [comment]
@rg-engineering Keine Auffälligkeiten mit 3.0.7 beim ersten Lauf 23:30 Uhr. Ich prüfe morgen früh das Log. Dann wurde die Instanz mind. 12 mal gestartet.
Danke  für den  schnellen Fix.

**Comment by Feuer-sturm** [comment]
@rg-engineering @Diginix Kann ich bestätigen. Seit gestern Nacht gab es keine weiteren Meldungen.
