### ISSUE TITLE
Fehlermeldung log unter 3.0.7

### ISSUE THREAD

**Issue by cTech1987** [rg-engineering/ioBroker.daswetter#98]
ich bekomme seit 3.0.7 folgende Fehlermeldungen:

daswetter.0	2021-05-18 11:30:27.274	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:27.106	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:26.956	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:26.747	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:26.579	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:26.415	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:26.249	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:26.027	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 1","role":"weather"}}} {"type":"channel","common":{"name":"Hour 1","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:25.711	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:25.453	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:25.317	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:25.130	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:24.903	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:24.700	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:24.127	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:23.941	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 1","role":"weather"}}} {"type":"channel","common":{"name":"Hour 1","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:23.592	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:23.432	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:23.255	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:23.083	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:21.117	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:20.947	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:20.767	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:20.594	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 1","role":"weather"}}} {"type":"channel","common":{"name":"Hour 1","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:19.894	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:19.264	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:18.981	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:18.709	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:18.264	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:18.007	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:17.532	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:14.980	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 1","role":"weather"}}} {"type":"channel","common":{"name":"Hour 1","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:14.298	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 8","role":"weather"}}} {"type":"channel","common":{"name":"Hour 8","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:14.034	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 7","role":"weather"}}} {"type":"channel","common":{"name":"Hour 7","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:13.768	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 6","role":"weather"}}} {"type":"channel","common":{"name":"Hour 6","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:13.488	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 5","role":"weather"}}} {"type":"channel","common":{"name":"Hour 5","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:13.262	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 4","role":"weather"}}} {"type":"channel","common":{"name":"Hour 4","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:12.971	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 3","role":"weather"}}} {"type":"channel","common":{"name":"Hour 3","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:12.779	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 2","role":"weather"}}} {"type":"channel","common":{"name":"Hour 2","role":"weather"},"native":{},"from":"system.adapter.daswet
daswetter.0	2021-05-18 11:30:12.521	warn	(29246) change object {"type":"channel","common":{"common":{"name":"Hour 1","role":"weather"}}} {"type":"channel","common":{"name":"Hour 1","role":"weather"},"native":{},"from":"system.adapter.daswet

**Comment by rg-engineering** [comment]
schau hier: #93 (vorletzter Kommentar), #96 und hier https://forum.iobroker.net/topic/5347/adapter-daswetter/1104
Lösche alle DasWetter-DP's und lasse sie neu anlegen....
